# Generated by Django 6.0.1 on 2026-01-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_assignment_selected_by_assignment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='tab_lock_violations',
            field=models.PositiveIntegerField(default=0, verbose_name='Tab Lock Violations'),
        ),
    ]
